FROM node:18-alpine as build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm run build

FROM node:18-alpine
WORKDIR /app/frontend
COPY --from=build /app/frontend .
ENV PORT=3020
CMD ["npm", "start"]
