FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY face_match_app ./face_match_app
CMD ["uvicorn", "face_match_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
